In [ ]:
# https://www.youtube.com/watch?v=DqtlR0y0suo

In [1]:
#Sending GET request through Insomnia API to nfl/odds page. Data does not contain props. Will have to run this script 2x


get_content_url= "https://content.unabated.com/markets/game-odds/v_gameodds.json?"
get_books_url = "https://api-k.unabated.com/api/users/settings"


Privilege_content = "https://content.unabated.com/markets/game-odds/b_gameodds.json"
#This one is when I am logged in

In [2]:
import requests
import pandas as pd

In [3]:
url = Privilege_content
#returns isPrivileged: true for premium sportsbooks

payload = ""
headers = {
    "authority": "content.unabated.com",
    "accept": "application/json, text/plain, */*",
    "accept-language": "en-US,en;q=0.9",
    "dnt": "1",
    "origin": "https://unabated.com",
    "referer": "https://unabated.com/",
    "sec-ch-ua": "^\^Google",
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": "^\^Windows^^",
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "same-site",
    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36",
    "x-amz-cf-v-id": "dNSob7rQOiJFE_59NDSm7tuZ6ed5MA_8w8CHVqr8tGSFYpgzEUqBuQ=="
}
#We can customize the headers we include ^ I left as it came
r = requests.request("GET", url, data=payload, headers=headers)

# print(r.json())
# all good

data = r.json()

marketSources = (data["marketSources"])
teams = (data["teams"])
gameOddsEvents = (data["gameOddsEvents"])

In [4]:
df_sportsbooks = pd.DataFrame(marketSources)
df_teams = pd.DataFrame(teams)
df_teams=df_teams.transpose()
df_ScoreId = pd.DataFrame.from_dict(gameOddsEvents, orient='index')
#  without orient='index' ... ValueError: All arrays must be of the same length
# https://stackoverflow.com/questions/40442014/python-pandas-valueerror-arrays-must-be-all-same-length

Transforming the SportsBooks Reference Table

In [7]:
df_sportsbooks

,name,logoUrl,thumbnailUrl,siteUrl,sortOrder,isActive,isPrivileged,statusId,createdOn,createdBy,modifiedOn,modifiedBy,id
0,Unabated,https://assets.unabated.com/sportsbooks/logos/...,None,None,10,True,True,0,2022-03-10T21:53:10.091792,None,2022-03-16T21:38:37.525262,6.0,49
1,Pinnacle - Delayed,None,None,None,50,True,False,2,2022-08-17T12:18:20.442277,None,2022-08-17T12:18:20.442277,NaN,58
2,Sporttrade,https://assets.unabated.com/sportsbooks/logos/...,https://assets.unabated.com/sportsbooks/thumbn...,None,70,True,False,1,2022-10-19T15:13:04.358892,None,2022-10-19T15:13:04.358892,NaN,67
3,theScore,https://assets.unabated.com/sportsbooks/logos/...,https://assets.unabated.com/sportsbooks/thumbn...,None,90,True,False,1,2022-08-25T18:02:36.780451,None,2022-08-25T18:02:36.780451,NaN,60
4,FanDuel - Delayed,https://assets.unabated.com/sportsbooks/logos/...,None,None,120,True,False,2,2022-06-09T14:45:56.826297,None,2022-06-09T14:45:56.826297,NaN,57
...,...,...,...,...,...,...,...,...,...,...,...,...,...
61,Caesars,https://assets.unabated.com/sportsbooks/logos/...,https://assets.unabated.com/sportsbooks/thumbn...,None,160,True,False,2,2021-07-07T02:13:52.730139,None,2022-11-08T15:00:33.647225,7.0,20
62,BetRivers,https://assets.unabated.com/sportsbooks/logos/...,https://assets.unabated.com/sportsbooks/thumbn...,None,260,True,False,2,2021-07-07T02:13:52.730139,None,2022-11-08T15:01:04.866956,7.0,17
63,Bookmaker,https://assets.unabated.com/sportsbooks/logos/...,https://assets.unabated.com/sportsbooks/thumbn...,None,30,True,False,1,2021-07-07T02:13:52.730139,None,2022-11-16T14:45:57.768571,6.0,8
64,Prophet Exchange,https://assets.unabated.com/sportsbooks/logos/...,https://assets.unabated.com/sportsbooks/thumbn...,None,80,True,False,1,2022-10-19T15:13:04.358892,None,2022-11-16T22:12:44.347255,70.0,66
65,Circa,https://assets.unabated.com/sportsbooks/logos/...,https://assets.unabated.com/sportsbooks/thumbn...,None,60,True,True,2,2021-07-07T02:13:52.730139,None,2022-11-25T13:16:52.580403,10.0,6

In [5]:
#Removing columns for building purposes 
#Note a bunch of other sportsbooks exist but are not shown on page. 

df_sb = pd.DataFrame().assign(Name=df_sportsbooks['name'],bookId=df_sportsbooks['id'],isActive=df_sportsbooks['isActive'],
isPrivileged=df_sportsbooks['isPrivileged'],statusId=df_sportsbooks['statusId'],modifiedDate=df_sportsbooks['modifiedOn'])

df_sb

,Name,bookId,isActive,isPrivileged,statusId,modifiedDate
0,Unabated,49,True,True,0,2022-03-16T21:38:37.525262
1,Pinnacle - Delayed,58,True,False,2,2022-08-17T12:18:20.442277
2,Sporttrade,67,True,False,1,2022-10-19T15:13:04.358892
3,theScore,60,True,False,1,2022-08-25T18:02:36.780451
4,FanDuel - Delayed,57,True,False,2,2022-06-09T14:45:56.826297
...,...,...,...,...,...,...
61,Caesars,20,True,False,2,2022-11-08T15:00:33.647225
62,BetRivers,17,True,False,2,2022-11-08T15:01:04.866956
63,Bookmaker,8,True,False,1,2022-11-16T14:45:57.768571
64,Prophet Exchange,66,True,False,1,2022-11-16T22:12:44.347255
65,Circa,6,True,True,2,2022-11-25T13:16:52.580403

In [6]:
#Creating Binary flags
# 
 
df_sb['nyBook']= 0
df_sb['sharpBook']=0
df_sb

,Name,bookId,isActive,isPrivileged,statusId,modifiedDate,nyBook,sharpBook
0,Unabated,49,True,True,0,2022-03-16T21:38:37.525262,0,0
1,Pinnacle - Delayed,58,True,False,2,2022-08-17T12:18:20.442277,0,0
2,Sporttrade,67,True,False,1,2022-10-19T15:13:04.358892,0,0
3,theScore,60,True,False,1,2022-08-25T18:02:36.780451,0,0
4,FanDuel - Delayed,57,True,False,2,2022-06-09T14:45:56.826297,0,0
...,...,...,...,...,...,...,...,...
61,Caesars,20,True,False,2,2022-11-08T15:00:33.647225,0,0
62,BetRivers,17,True,False,2,2022-11-08T15:01:04.866956,0,0
63,Bookmaker,8,True,False,1,2022-11-16T14:45:57.768571,0,0
64,Prophet Exchange,66,True,False,1,2022-11-16T22:12:44.347255,0,0
65,Circa,6,True,True,2,2022-11-25T13:16:52.580403,0,0

In [7]:
df_nyBooks= pd.DataFrame(
    {"Name" : ["Caesars", "DraftKings", "FanDuel", "FanDuel - Delayed", "BetMGM", "PointsBet", "BetRivers", "WynnBet", "Resorts", "BallyBet"],
    'nyBook': [1,1,1,1,1,1,1,1,1,1]
    }
)
df_sharpBooks = pd.DataFrame(
    {"Name" :['Unabated','Pinnacle','Pinnacle - Delayed','Bookmaker','Prophet Exchange'],
    'sharpBook': [1,1,1,1,1]
    }
)

In [8]:
df_sb=df_sb.set_index('Name')
df2 = df_nyBooks.set_index('Name')
df_sb.update(df2)

df3=df_sharpBooks.set_index('Name')
df_sb.update(df3)

In [9]:
df_sb

#This is the Sportsbook Reference table. Might also want to change the number format for the dates

,bookId,isActive,isPrivileged,statusId,modifiedDate,nyBook,sharpBook
Name,,,,,,,
Unabated,49,True,True,0,2022-03-16T21:38:37.525262,0.0,1.0
Pinnacle - Delayed,58,True,False,2,2022-08-17T12:18:20.442277,0.0,1.0
Sporttrade,67,True,False,1,2022-10-19T15:13:04.358892,0.0,0.0
theScore,60,True,False,1,2022-08-25T18:02:36.780451,0.0,0.0
FanDuel - Delayed,57,True,False,2,2022-06-09T14:45:56.826297,1.0,0.0
...,...,...,...,...,...,...,...
Caesars,20,True,False,2,2022-11-08T15:00:33.647225,1.0,0.0
BetRivers,17,True,False,2,2022-11-08T15:01:04.866956,1.0,0.0
Bookmaker,8,True,False,1,2022-11-16T14:45:57.768571,0.0,1.0
Prophet Exchange,66,True,False,1,2022-11-16T22:12:44.347255,0.0,1.0
Circa,6,True,True,2,2022-11-25T13:16:52.580403,0.0,0.0

In [10]:
print(df_sb['nyBook'].value_counts())
print(df_sb['sharpBook'].value_counts())

0.0    56
1.0    10
Name: nyBook, dtype: int64
0.0    61
1.0     5
Name: sharpBook, dtype: int64

In [338]:
df_sb.to_csv('sportsbooksTable.csv')

________________________________________________________________________________________


Now we create the Teams table. 

The eventId is the unique gameID which two teams will share. Not positive on what sideId is yet, but it distinguishes one team from another inside of a cell.

In [11]:
df_teams

,eventId,sideId,score,rotationNumber,name,abbreviation,logoUrl,leagueId,divisionId,divisionAbbreviation,conferenceAbbreviation,teamPeople,createdOn,createdBy,modifiedOn,modifiedBy,id
2,21884,1,None,456,Atlanta Falcons,ATL,https://assets.unabated.com/teams/logos/nfl/at...,1,8,None,None,[],0001-01-01T00:00:00,None,0001-01-01T00:00:00,None,2
25,21884,0,None,455,Pittsburgh Steelers,PIT,https://assets.unabated.com/teams/logos/nfl/pi...,1,3,None,None,[],0001-01-01T00:00:00,None,0001-01-01T00:00:00,None,25
6,21885,1,None,466,Chicago Bears,CHI,https://assets.unabated.com/teams/logos/nfl/ch...,1,7,None,None,[],0001-01-01T00:00:00,None,0001-01-01T00:00:00,None,6
12,21885,0,None,465,Green Bay Packers,GB,https://assets.unabated.com/teams/logos/nfl/gb...,1,7,None,None,[],0001-01-01T00:00:00,None,0001-01-01T00:00:00,None,12
11,21886,1,None,460,Detroit Lions,DET,https://assets.unabated.com/teams/logos/nfl/de...,1,7,None,None,[],0001-01-01T00:00:00,None,0001-01-01T00:00:00,None,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
535,39040,1,None,306516,NC Asheville,UNCA,None,4,None,None,None,[],0001-01-01T00:00:00,None,0001-01-01T00:00:00,None,535
1202,39073,0,None,308947,Valparaiso,VAL,None,2,10,None,None,[],0001-01-01T00:00:00,None,0001-01-01T00:00:00,None,1202
661,39073,1,None,308948,New Mexico State,NMS,https://assets.unabated.com/teams/logos/cfb/NM...,2,9,None,None,[],0001-01-01T00:00:00,None,0001-01-01T00:00:00,None,661
524,39139,1,0,None,UC San Diego,None,None,4,None,None,None,[],0001-01-01T00:00:00,None,0001-01-01T00:00:00,None,524
124,39139,0,0,None,Bethesda Flames,None,None,4,None,None,None,[],0001-01-01T00:00:00,None,0001-01-01T00:00:00,None,124

In [12]:
#slimming down

df_teams_refined = pd.DataFrame().assign(Name=df_teams['name'],abbreviation=df_teams['abbreviation'],TeamId=df_teams['id'],
eventId=df_teams['eventId'],sideId=df_teams['sideId'],leagueId=df_teams['leagueId'],divisionId=df_teams['divisionId'],
modifiedDate=df_teams['modifiedOn'])

df_teams_refined
#This is our Teams Table

,Name,abbreviation,TeamId,eventId,sideId,leagueId,divisionId,modifiedDate
2,Atlanta Falcons,ATL,2,21884,1,1,8,0001-01-01T00:00:00
25,Pittsburgh Steelers,PIT,25,21884,0,1,3,0001-01-01T00:00:00
6,Chicago Bears,CHI,6,21885,1,1,7,0001-01-01T00:00:00
12,Green Bay Packers,GB,12,21885,0,1,7,0001-01-01T00:00:00
11,Detroit Lions,DET,11,21886,1,1,7,0001-01-01T00:00:00
...,...,...,...,...,...,...,...,...
535,NC Asheville,UNCA,535,39040,1,4,None,0001-01-01T00:00:00
1202,Valparaiso,VAL,1202,39073,0,2,10,0001-01-01T00:00:00
661,New Mexico State,NMS,661,39073,1,2,9,0001-01-01T00:00:00
524,UC San Diego,None,524,39139,1,4,None,0001-01-01T00:00:00
124,Bethesda Flames,None,124,39139,0,4,None,0001-01-01T00:00:00

In [13]:
#worked backward to get this. 

league_dict = {
    1:'NFL',
    2:'CFB',
    3:'NBA',
    4:'NCAAB',
    5:'MLB',
    6:'NHL'
    }

In [341]:
df_teams_refined.to_csv('df_teams_ref_out.csv')

__________________________________________________________________________________

Now we tackle the GameOdd Table

In [6]:
#get a list of all leagues and pt's to iterate over
gameOddsEvents.keys()

dict_keys(['lg1:pt1:pregame', 'lg1:pt4:pregame', 'lg1:pt5:pregame', 'lg1:pt6:pregame', 'lg1:pt7:pregame', 'lg1:pt2:pregame', 'lg1:pt3:pregame', 'lg6:pt1:live', 'lg6:pt8:live', 'lg6:pt9:live', 'lg6:pt10:live', 'lg6:pt1:pregame', 'lg6:pt10:pregame', 'lg6:pt9:pregame', 'lg6:pt8:pregame', 'lg6:pt4:pregame', 'lg6:pt5:pregame', 'lg6:pt6:pregame', 'lg3:pt1:live', 'lg3:pt4:live', 'lg3:pt5:live', 'lg3:pt6:live', 'lg3:pt7:live', 'lg3:pt2:live', 'lg3:pt3:live', 'lg3:pt1:pregame', 'lg3:pt5:pregame', 'lg3:pt4:pregame', 'lg3:pt6:pregame', 'lg3:pt3:pregame', 'lg3:pt2:pregame', 'lg3:pt7:pregame', 'lg4:pt1:pregame', 'lg4:pt4:pregame', 'lg4:pt5:pregame', 'lg4:pt6:pregame', 'lg4:pt7:pregame', 'lg4:pt2:pregame', 'lg4:pt3:pregame', 'lg4:pt1:live', 'lg4:pt4:live', 'lg4:pt5:live', 'lg4:pt6:live', 'lg4:pt7:live', 'lg4:pt2:live', 'lg4:pt3:live', 'lg2:pt1:pregame', 'lg2:pt4:pregame', 'lg2:pt5:pregame', 'lg2:pt6:pregame', 'lg2:pt7:pregame', 'lg2:pt2:pregame', 'lg2:pt3:pregame', 'lg2:pt1:live', 'lg2:pt4:live', 'lg2:pt5:live', 'lg2:pt6:live', 'lg2:pt7:live', 'lg2:pt2:live', 'lg2:pt3:live'])

In [62]:
gameOddsEvents2 = (data["gameOddsEvents"]["lg1:pt1:pregame"]) #we will need to iterate acrosss all of the lg...pt....
#this is a list with each element containing a new eventId aka gameId. Each gameId will have multiple gameOdds(bettypes) and period time
#confirmed that this list contains every unique game on the nfl/odds page. Note this is not the props data. 

##we can use the eventTeams dict -> id to join the Teams Table and determine which sport we're playing.

df_gameOddsEvents2 = pd.DataFrame(gameOddsEvents2) #THIS IS HOW WE WANT TO DO IT
#now we need to break down the eventTeams and the gameOddsMarketSourcesLines (THIS IS WHERE ODDS)

df_gameOddsEvents2

,eventId,eventStart,eventEnd,statusId,gameClock,periodTypeId,overtimeNumber,eventTeams,gameOddsMarketSourcesLines
0,21884,2022-12-04T18:00:00,None,1,None,None,None,"{'1': {'id': 2, 'rotationNumber': 456, 'score'...",{'si1:ms1:an0': {'bt2': {'marketLineId': 67200...
1,21885,2022-12-04T18:00:00,None,1,None,None,None,"{'1': {'id': 6, 'rotationNumber': 466, 'score'...",{'si1:ms4:an0': {'bt1': {'marketLineId': 20055...
2,21886,2022-12-04T18:00:00,None,1,None,None,None,"{'1': {'id': 11, 'rotationNumber': 460, 'score...",{'si1:ms1:an0': {'bt1': {'marketLineId': 67200...
3,21887,2022-12-04T18:00:00,None,1,None,None,None,"{'1': {'id': 18, 'rotationNumber': 452, 'score...",{'si1:ms1:an0': {'bt1': {'marketLineId': 67200...
4,21888,2022-12-04T18:00:00,None,1,None,None,None,"{'1': {'id': 21, 'rotationNumber': 462, 'score...",{'si1:ms11:an2': {'bt3': {'marketLineId': 2033...
5,21889,2022-12-04T18:00:00,None,1,None,None,None,"{'0': {'id': 31, 'rotationNumber': 457, 'score...",{'si1:ms1:an0': {'bt1': {'marketLineId': 67200...
6,21890,2022-12-04T18:00:00,None,1,None,None,None,"{'1': {'id': 3, 'rotationNumber': 454, 'score'...",{'si1:ms1:an0': {'bt3': {'marketLineId': 18697...
7,21891,2022-12-04T18:00:00,None,1,None,None,None,"{'1': {'id': 13, 'rotationNumber': 464, 'score...",{'si1:ms62:an0': {'bt3': {'marketLineId': 2026...
8,21892,2022-12-04T21:05:00,None,1,None,None,None,"{'1': {'id': 29, 'rotationNumber': 468, 'score...",{'si1:ms1:an0': {'bt1': {'marketLineId': 67200...
9,21893,2022-12-04T21:05:00,None,1,None,None,None,"{'0': {'id': 17, 'rotationNumber': 469, 'score...",{'si1:ms1:an0': {'bt1': {'marketLineId': 67200...
10,21894,2022-12-04T21:25:00,None,1,None,None,None,"{'1': {'id': 7, 'rotationNumber': 474, 'score'...",{'si1:ms1:an0': {'bt1': {'marketLineId': 67200...
11,21895,2022-12-04T21:25:00,None,1,None,None,None,"{'1': {'id': 23, 'rotationNumber': None, 'scor...",{'si1:ms1:an0': {'bt1': {'marketLineId': 67200...
12,21896,2022-12-05T01:20:00,None,1,None,None,None,"{'1': {'id': 9, 'rotationNumber': 476, 'score'...",{'si1:ms9:an0': {'bt1': {'marketLineId': 20261...
13,21897,2022-12-06T01:15:00,None,1,None,None,None,"{'1': {'id': 30, 'rotationNumber': 478, 'score...",{'si1:ms1:an0': {'bt1': {'marketLineId': 67200...
14,21898,2022-12-09T01:15:00,None,1,None,None,None,"{'1': {'id': 29, 'rotationNumber': None, 'scor...",{'si1:ms1:an0': {'bt1': {'marketLineId': 67201...
15,21899,2022-12-11T18:00:00,None,1,None,None,None,"{'1': {'id': 4, 'rotationNumber': 108, 'score'...",{'si1:ms1:an0': {'bt1': {'marketLineId': 67201...
16,21900,2022-12-11T18:00:00,None,1,None,None,None,"{'1': {'id': 7, 'rotationNumber': 114, 'score'...",{'si0:ms27:an0': {'bt3': {'marketLineId': 2051...
17,21901,2022-12-11T18:00:00,None,1,None,None,None,"{'1': {'id': 9, 'rotationNumber': 118, 'score'...",{'si1:ms28:an0': {'bt2': {'marketLineId': 2026...
18,21902,2022-12-11T18:00:00,None,1,None,None,None,"{'1': {'id': 11, 'rotationNumber': 106, 'score...",{'si1:ms1:an0': {'bt2': {'marketLineId': 67201...
19,21903,2022-12-11T18:00:00,None,1,None,None,None,"{'1': {'id': 31, 'rotationNumber': 116, 'score...",{'si1:ms1:an0': {'bt2': {'marketLineId': 67201...
20,21904,2022-12-11T18:00:00,None,1,None,None,None,"{'1': {'id': 21, 'rotationNumber': 112, 'score...",{'si1:ms1:an0': {'bt2': {'marketLineId': 67201...
21,21905,2022-12-11T18:00:00,None,1,None,None,None,"{'1': {'id': 25, 'rotationNumber': 110, 'score...",{'si1:ms1:an0': {'bt2': {'marketLineId': 67201...
22,21906,2022-12-12T01:20:00,None,1,None,None,None,"{'1': {'id': 26, 'rotationNumber': 120, 'score...",{'si1:ms1:an0': {'bt2': {'marketLineId': 67201...
23,21907,2022-12-11T21:25:00,None,1,None,None,None,"{'1': {'id': 27, 'rotationNumber': 124, 'score...",{'si1:ms1:an0': {'bt2': {'marketLineId': 67201...
24,21908,2022-12-11T21:25:00,None,1,None,None,None,"{'1': {'id': 28, 'rotationNumber': 122, 'score...",{'si1:ms1:an0': {'bt2': {'marketLineId': 67201...
25,21909,2022-12-11T21:05:00,None,1,None,None,None,"{'1': {'id': 10, 'rotationNumber': 126, 'score...",{'si1:ms1:an0': {'bt2': {'marketLineId': 67201...
26,21910,2022-12-13T01:15:00,None,1,None,None,None,"{'0': {'id': 19, 'rotationNumber': 127, 'score...",{'si1:ms1:an0': {'bt2': {'marketLineId': 67201...
27,21911,2022-12-16T01:15:00,None,1,None,None,None,"{'1': {'id': 28, 'rotationNumber': None, 'scor...",{'si1:ms1:an0': {'bt2': {'marketLineId': 67201...

In [60]:
gameOdds_EventsTeams = (data["gameOddsEvents"]["lg1:pt1:pregame"][0]['eventTeams'])
print(gameOdds_EventsTeams)
#{'1': {'id': 27, 'rotationNumber': 470, 'score': None}, 
# '0': {'id': 17, 'rotationNumber': 469, 'score': None}}

{'1': {'id': 2, 'rotationNumber': 456, 'score': None}, '0': {'id': 25, 'rotationNumber': 455, 'score': None}}

In [59]:
gameOddsEvents3 = (data["gameOddsEvents"]["lg1:pt1:pregame"][0]['gameOddsMarketSourcesLines']) 

print(type(gameOddsEvents3))
print(len(gameOddsEvents3))
#the odds data is held here. I believe the marketLineId is the unique bet id

<class 'dict'>
68

In [10]:
df_gameOdds = pd.DataFrame.from_dict(gameOddsEvents3, orient='index')

df_gameOdds  # 3 columns... 3 bet parameters?

,bt2,bt1,bt3
si1:ms1:an0,"{'marketLineId': 67200944, 'isBlurred': False,...","{'marketLineId': 67200954, 'isBlurred': False,...","{'marketLineId': 186967224, 'isBlurred': False..."
si1:ms2:an0,"{'marketLineId': 186917435, 'isBlurred': False...","{'marketLineId': 186917429, 'isBlurred': False...","{'marketLineId': 186917426, 'isBlurred': False..."
si1:ms3:an0,"{'marketLineId': 202596007, 'isBlurred': False...","{'marketLineId': 202596005, 'isBlurred': False...","{'marketLineId': 202596009, 'isBlurred': False..."
si1:ms4:an0,"{'marketLineId': 200686536, 'isBlurred': False...","{'marketLineId': 200686323, 'isBlurred': False...","{'marketLineId': 200686537, 'isBlurred': False..."
si1:ms6:an0,"{'marketLineId': 200253585, 'isBlurred': True,...","{'marketLineId': 200662357, 'isBlurred': True,...","{'marketLineId': 200253590, 'isBlurred': True,..."
...,...,...,...
si0:ms63:an0,"{'marketLineId': 203515948, 'isBlurred': False...",NaN,NaN
si0:ms64:an0,"{'marketLineId': 204592214, 'isBlurred': False...",NaN,NaN
si0:ms65:an0,"{'marketLineId': 203707013, 'isBlurred': False...",NaN,NaN
si1:ms52:an0,NaN,"{'marketLineId': 202550322, 'isBlurred': False...","{'marketLineId': 202550324, 'isBlurred': False..."
si0:ms52:an0,NaN,"{'marketLineId': 202550323, 'isBlurred': False...","{'marketLineId': 202550325, 'isBlurred': False..."

In [11]:
#THIS IS THE MOST GRANULAR ITEM. This represents a unique bet we can enter. 

df_gameOdds.iat[0,0]

{'marketLineId': 67200944,
 'isBlurred': False,
 'marketId': 473551,
 'marketSourceId': 1,
 'points': -1.0,
 'price': 100,
 'americanPrice': 100,
 'sourcePrice': 2.0,
 'sourceFormat': 2,
 'alternateNumber': 0,
 'statusId': 1,
 'sequenceNumber': 1670005596792,
 'overrideType': None,
 'includePeg': True,
 'stn': None,
 'cr': -110.3,
 'ib': True,
 'tm': None,
 'createdOn': '2022-07-26T14:41:34.769068',
 'createdBy': -25,
 'modifiedOn': '2022-12-02T18:26:38.597161',
 'modifiedBy': -25,
 'id': None}

In [25]:
df_bt1 = df_gameOdds['bt1'].apply(pd.Series)
df_bt2 = df_gameOdds['bt2'].apply(pd.Series)
df_bt3 = df_gameOdds['bt3'].apply(pd.Series)

In [46]:
df_bt1['bet'] = 'bt1'
df_bt2['bet'] = 'bt2'
df_bt3['bet'] = 'bt3'

,marketLineId,isBlurred,marketId,marketSourceId,points,price,americanPrice,sourcePrice,sourceFormat,alternateNumber,...,cr,ib,tm,createdOn,createdBy,modifiedOn,modifiedBy,id,0,bet
si1:ms1:an0,67200954.0,False,632419.0,1.0,0.0,-105.0,-105.0,1.952381,2.0,0.0,...,-105.0,True,NaN,2022-07-26T14:41:34.838632,-25.0,2022-12-02T18:26:38.615293,-25.0,NaN,NaN,bt1
si1:ms2:an0,186917429.0,False,632419.0,2.0,0.0,-106.0,-106.0,-106.000000,1.0,0.0,...,-106.0,True,NaN,2022-11-22T20:01:01.754548,-20.0,2022-12-02T21:29:58.144243,-20.0,NaN,NaN,bt1
si1:ms3:an0,202596005.0,False,632419.0,3.0,NaN,-107.0,-107.0,-107.000000,1.0,0.0,...,-107.0,True,NaN,2022-11-29T17:06:23.120684,-11.0,2022-12-02T21:48:15.761653,-11.0,NaN,NaN,bt1
si1:ms4:an0,200686323.0,False,632419.0,4.0,NaN,-105.0,-105.0,1.952380,2.0,0.0,...,-105.0,True,NaN,2022-11-28T15:03:10.643323,-2.0,2022-11-29T19:23:02.546312,-2.0,NaN,NaN,bt1
si1:ms6:an0,200662357.0,True,632419.0,6.0,NaN,-110.0,-110.0,100.000000,1.0,0.0,...,NaN,True,NaN,2022-11-28T14:33:16.902206,-16.0,2022-12-01T15:42:04.334376,-16.0,NaN,NaN,bt1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
si0:ms63:an0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,bt1
si0:ms64:an0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,bt1
si0:ms65:an0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,bt1
si1:ms52:an0,202550322.0,False,632419.0,52.0,NaN,100.0,100.0,100.000000,1.0,0.0,...,100.0,False,NaN,2022-11-29T15:21:53.847877,-11.0,2022-11-30T09:48:30.786877,-11.0,NaN,NaN,bt1
si0:ms52:an0,202550323.0,False,632437.0,52.0,NaN,-105.0,-105.0,-105.000000,1.0,0.0,...,-105.0,False,NaN,2022-11-29T15:21:53.860685,-11.0,2022-12-01T10:31:09.899754,-11.0,NaN,NaN,bt1

In [51]:
df_bt3

,marketLineId,isBlurred,marketId,marketSourceId,points,price,americanPrice,sourcePrice,sourceFormat,alternateNumber,...,cr,ib,tm,createdOn,createdBy,modifiedOn,modifiedBy,id,0,bet
si1:ms1:an0,186967224.0,False,632784.0,1.0,43.0,-110.0,-110.0,1.909091,2.0,0.0,...,-110.0,True,NaN,2022-11-22T21:19:44.457145,-25.0,2022-12-02T21:17:57.480618,-25.0,NaN,NaN,bt3
si1:ms2:an0,186917426.0,False,632784.0,2.0,42.5,-106.0,-106.0,-106.000000,1.0,0.0,...,-113.9,True,NaN,2022-11-22T20:01:01.712412,-20.0,2022-12-02T21:29:58.121285,-20.0,NaN,NaN,bt3
si1:ms3:an0,202596009.0,False,632784.0,3.0,42.5,-107.0,-107.0,-107.000000,1.0,0.0,...,-114.9,True,NaN,2022-11-29T17:06:23.201262,-11.0,2022-12-02T21:41:44.408377,-11.0,NaN,NaN,bt3
si1:ms4:an0,200686537.0,False,632784.0,4.0,42.5,-110.0,-110.0,1.909090,2.0,0.0,...,-118.2,True,NaN,2022-11-28T15:03:59.789939,-2.0,2022-12-02T21:19:18.485003,-2.0,NaN,NaN,bt3
si1:ms6:an0,200253590.0,True,632784.0,6.0,-1.0,-110.0,-110.0,-110.000000,1.0,0.0,...,NaN,True,NaN,2022-11-28T01:39:52.697635,-16.0,2022-12-02T21:17:58.046371,-16.0,NaN,NaN,bt3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
si0:ms63:an0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,bt3
si0:ms64:an0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,bt3
si0:ms65:an0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,bt3
si1:ms52:an0,202550324.0,False,632784.0,52.0,41.5,104.0,104.0,104.000000,1.0,0.0,...,-109.9,False,NaN,2022-11-29T15:21:53.873684,-11.0,2022-12-01T15:56:23.706825,-11.0,NaN,NaN,bt3
si0:ms52:an0,202550325.0,False,632790.0,52.0,41.5,-119.0,-119.0,-119.000000,1.0,0.0,...,-103.7,False,NaN,2022-11-29T15:21:53.8861,-11.0,2022-12-01T16:29:58.75062,-11.0,NaN,NaN,bt3

In [48]:
df_bt1

#This table holds all the bets in lg1:pt1:pregame

,marketLineId,isBlurred,marketId,marketSourceId,points,price,americanPrice,sourcePrice,sourceFormat,alternateNumber,...,cr,ib,tm,createdOn,createdBy,modifiedOn,modifiedBy,id,0,bet
si1:ms1:an0,67200954.0,False,632419.0,1.0,0.0,-105.0,-105.0,1.952381,2.0,0.0,...,-105.0,True,NaN,2022-07-26T14:41:34.838632,-25.0,2022-12-02T18:26:38.615293,-25.0,NaN,NaN,bt1
si1:ms2:an0,186917429.0,False,632419.0,2.0,0.0,-106.0,-106.0,-106.000000,1.0,0.0,...,-106.0,True,NaN,2022-11-22T20:01:01.754548,-20.0,2022-12-02T21:29:58.144243,-20.0,NaN,NaN,bt1
si1:ms3:an0,202596005.0,False,632419.0,3.0,NaN,-107.0,-107.0,-107.000000,1.0,0.0,...,-107.0,True,NaN,2022-11-29T17:06:23.120684,-11.0,2022-12-02T21:48:15.761653,-11.0,NaN,NaN,bt1
si1:ms4:an0,200686323.0,False,632419.0,4.0,NaN,-105.0,-105.0,1.952380,2.0,0.0,...,-105.0,True,NaN,2022-11-28T15:03:10.643323,-2.0,2022-11-29T19:23:02.546312,-2.0,NaN,NaN,bt1
si1:ms6:an0,200662357.0,True,632419.0,6.0,NaN,-110.0,-110.0,100.000000,1.0,0.0,...,NaN,True,NaN,2022-11-28T14:33:16.902206,-16.0,2022-12-01T15:42:04.334376,-16.0,NaN,NaN,bt1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
si0:ms63:an0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,bt1
si0:ms64:an0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,bt1
si0:ms65:an0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,bt1
si1:ms52:an0,202550322.0,False,632419.0,52.0,NaN,100.0,100.0,100.000000,1.0,0.0,...,100.0,False,NaN,2022-11-29T15:21:53.847877,-11.0,2022-11-30T09:48:30.786877,-11.0,NaN,NaN,bt1
si0:ms52:an0,202550323.0,False,632437.0,52.0,NaN,-105.0,-105.0,-105.000000,1.0,0.0,...,-105.0,False,NaN,2022-11-29T15:21:53.860685,-11.0,2022-12-01T10:31:09.899754,-11.0,NaN,NaN,bt1

In [49]:
pd.concat([df_bt1,df_bt2,df_bt3])
# contains all bet odds for the first eventId row in gameOddsEvents2
#the marketId changes for each bt1,bt2,bt3

,marketLineId,isBlurred,marketId,marketSourceId,points,price,americanPrice,sourcePrice,sourceFormat,alternateNumber,...,cr,ib,tm,createdOn,createdBy,modifiedOn,modifiedBy,id,0,bet
si1:ms1:an0,67200954.0,False,632419.0,1.0,0.0,-105.0,-105.0,1.952381,2.0,0.0,...,-105.0,True,NaN,2022-07-26T14:41:34.838632,-25.0,2022-12-02T18:26:38.615293,-25.0,NaN,NaN,bt1
si1:ms2:an0,186917429.0,False,632419.0,2.0,0.0,-106.0,-106.0,-106.000000,1.0,0.0,...,-106.0,True,NaN,2022-11-22T20:01:01.754548,-20.0,2022-12-02T21:29:58.144243,-20.0,NaN,NaN,bt1
si1:ms3:an0,202596005.0,False,632419.0,3.0,NaN,-107.0,-107.0,-107.000000,1.0,0.0,...,-107.0,True,NaN,2022-11-29T17:06:23.120684,-11.0,2022-12-02T21:48:15.761653,-11.0,NaN,NaN,bt1
si1:ms4:an0,200686323.0,False,632419.0,4.0,NaN,-105.0,-105.0,1.952380,2.0,0.0,...,-105.0,True,NaN,2022-11-28T15:03:10.643323,-2.0,2022-11-29T19:23:02.546312,-2.0,NaN,NaN,bt1
si1:ms6:an0,200662357.0,True,632419.0,6.0,NaN,-110.0,-110.0,100.000000,1.0,0.0,...,NaN,True,NaN,2022-11-28T14:33:16.902206,-16.0,2022-12-01T15:42:04.334376,-16.0,NaN,NaN,bt1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
si0:ms63:an0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,bt3
si0:ms64:an0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,bt3
si0:ms65:an0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,bt3
si1:ms52:an0,202550324.0,False,632784.0,52.0,41.5,104.0,104.0,104.000000,1.0,0.0,...,-109.9,False,NaN,2022-11-29T15:21:53.873684,-11.0,2022-12-01T15:56:23.706825,-11.0,NaN,NaN,bt3
si0:ms52:an0,202550325.0,False,632790.0,52.0,41.5,-119.0,-119.0,-119.000000,1.0,0.0,...,-103.7,False,NaN,2022-11-29T15:21:53.8861,-11.0,2022-12-01T16:29:58.75062,-11.0,NaN,NaN,bt3

In [64]:
df_gameOddsEvents2['eventTeams']['id'].apply(pd.Series)

KeyError: 'id'

In [35]:
# pd.concat([df_gameOdds.drop(['bt1'], axis=1), df_gameOdds['bt1'].apply(pd.Series)], axis=1)

# https://stackoverflow.com/questions/38231591/split-explode-a-column-of-dictionaries-into-separate-columns-with-pandas

,bt2,bt3,marketLineId,isBlurred,marketId,marketSourceId,points,price,americanPrice,sourcePrice,...,stn,cr,ib,tm,createdOn,createdBy,modifiedOn,modifiedBy,id,0
si1:ms1:an0,"{'marketLineId': 67200944, 'isBlurred': False,...","{'marketLineId': 186967224, 'isBlurred': False...",67200954.0,False,632419.0,1.0,0.0,-105.0,-105.0,1.952381,...,NaN,-105.0,True,NaN,2022-07-26T14:41:34.838632,-25.0,2022-12-02T18:26:38.615293,-25.0,NaN,NaN
si1:ms2:an0,"{'marketLineId': 186917435, 'isBlurred': False...","{'marketLineId': 186917426, 'isBlurred': False...",186917429.0,False,632419.0,2.0,0.0,-106.0,-106.0,-106.000000,...,NaN,-106.0,True,NaN,2022-11-22T20:01:01.754548,-20.0,2022-12-02T21:29:58.144243,-20.0,NaN,NaN
si1:ms3:an0,"{'marketLineId': 202596007, 'isBlurred': False...","{'marketLineId': 202596009, 'isBlurred': False...",202596005.0,False,632419.0,3.0,NaN,-107.0,-107.0,-107.000000,...,NaN,-107.0,True,NaN,2022-11-29T17:06:23.120684,-11.0,2022-12-02T21:48:15.761653,-11.0,NaN,NaN
si1:ms4:an0,"{'marketLineId': 200686536, 'isBlurred': False...","{'marketLineId': 200686537, 'isBlurred': False...",200686323.0,False,632419.0,4.0,NaN,-105.0,-105.0,1.952380,...,NaN,-105.0,True,NaN,2022-11-28T15:03:10.643323,-2.0,2022-11-29T19:23:02.546312,-2.0,NaN,NaN
si1:ms6:an0,"{'marketLineId': 200253585, 'isBlurred': True,...","{'marketLineId': 200253590, 'isBlurred': True,...",200662357.0,True,632419.0,6.0,NaN,-110.0,-110.0,100.000000,...,NaN,NaN,True,NaN,2022-11-28T14:33:16.902206,-16.0,2022-12-01T15:42:04.334376,-16.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
si0:ms63:an0,"{'marketLineId': 203515948, 'isBlurred': False...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
si0:ms64:an0,"{'marketLineId': 204592214, 'isBlurred': False...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
si0:ms65:an0,"{'marketLineId': 203707013, 'isBlurred': False...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
si1:ms52:an0,NaN,"{'marketLineId': 202550324, 'isBlurred': False...",202550322.0,False,632419.0,52.0,NaN,100.0,100.0,100.000000,...,NaN,100.0,False,NaN,2022-11-29T15:21:53.847877,-11.0,2022-11-30T09:48:30.786877,-11.0,NaN,NaN
si0:ms52:an0,NaN,"{'marketLineId': 202550325, 'isBlurred': False...",202550323.0,False,632437.0,52.0,NaN,-105.0,-105.0,-105.000000,...,NaN,-105.0,False,NaN,2022-11-29T15:21:53.860685,-11.0,2022-12-01T10:31:09.899754,-11.0,NaN,NaN